spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jsonbDemo
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    url: jdbc:postgresql://localhost:5432/jsonbDemo
    schemas: public
    user: postgres
    password: root
    baselineOnMigrate: true
    enabled: true
    validate-on-migrate: true
